org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 26.2
minecraft_version_supported = [26.1,26.2]
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1(2)
archives_base_name = MoreLecternVariants

## Mod Properties

mod_id=lolmlv
mod_name=More Lectern Variants
mod_name_short=More Lectern Variants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.9.3
mod_group_id=de.pnku.mlv
mod_author=pnku
mod_description=Adding lectern variants to Minecraft

# Quad Properties
quad_version=1.2.0