org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 1.21.1
minecraft_version_supported = [1.21,1.21.1]
minecraft_version_upper = 1.21.4

# File Name
minecraft_version_name = 1.21(.1)
archives_base_name = MoreLecternVariants

## Mod Properties

mod_id=lolmlv
mod_name=More Lectern Variants
mod_name_short=More Lectern Variants
mod_license=MIT
mod_version=1.9.0
mod_group_id=de.pnku.mlv
mod_authors=pnku, LieOnLion
mod_description=Adding lectern variants to Minecraft

# Quad Properties
quad_version=1.2.0